### ISSUE TITLE
already connect wallet

### ISSUE THREAD

**Issue by gamang** [codenewinsight/PAWS-Telegram-Bot#1]
already connect the wallet , just need to run it , node paws.js cant work

**Comment by Elsiehwoods** [comment]
@gamang Make sure Node.js is installed correctly. You can check the version with:
   ```bash
   node -v
   ```
   If it's not installed, download and install the latest version from [nodejs.org](https://nodejs.org/).

**Comment by codenewinsight** [comment]
just put some random wallet in data. it will not connect wallet again
